"""empty message

Revision ID: 64674ee0e884
Revises: 670e6386acc0
Create Date: 2021-04-15 15:03:49.393136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64674ee0e884'
down_revision = '670e6386acc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'title')
    op.drop_column('task', 'goal_id')
    op.drop_column('task', 'description')
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
